Updated gi18n-checkup to match latest correct and working version

diff --git a/bin/gi18n-checkup b/bin/gi18n-checkup
--- a/bin/gi18n-checkup
+++ b/bin/gi18n-checkup
@@ -5,13 +5,12 @@ set +e
 export GOPATH=$HOME/go
 export PATH=$PATH:$GOPATH/bin
 
-# This doesn't compile automatically, so fails
-# go get -u github.com/maximilien/i18n4go
-# OUTPUT=$?
-# if [ $OUTPUT -ne 0 ]; then
-#   printf "Cannot install latest gi18n tool to verify strings:\n${OUTPUT}"
-#   exit 1
-# fi
+go get -u github.com/maximilien/i18n4go/i18n4go
+OUTPUT=$?
+if [ $OUTPUT -ne 0 ]; then
+  printf "Cannot install latest gi18n tool to verify strings:\n${OUTPUT}"
+  exit 1
+fi
 
 OUTPUT=`i18n4go -c checkup`
 
